### PR TITLE
Add Dockerfile for ARMv7 and update README

### PR DESCRIPTION
**Pull request by pwt**
I created and tested a Dockerfile suitable for use on ARMv7 devices, such as Raspberry Pis.

### CODE REVIEW

**Comment by chrisns** [comment]
Hey @pwt this is great, thanks for your contribution. do you know if I can build this in travis/dockerhub/some other preferably free CI so the docker images get updated?
thanks

**Comment by pwt** [comment]
Thanks @chrisns . It seems to be possible to build ARM images on Docker Hub (and elsewhere) by running under QEMU. I'll investigate.

**Comment by pwt** [comment]
I have the arm32v7 images being successfully built on Docker Hub using the approach documented at https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

The images appear to run correctly on my Raspberry Pi. I need to do some tidying up before this is ready.

**Comment by pwt** [comment]
Hi @chrisns : I think this is ready to go now. There are Dockerfiles for native ARM builds and x86 builds, in separate directories. Both have worked OK under light testing on my Raspberry Pi 3+, end-to-end from build to deployment. I've tested the x86 builds locally (Ubuntu 18.04) and on Docker Hub triggering off GitHub commits (specify `/arm32v7-crossbuild` as the Dockerfile Location). Let me know if there's any thing else you'd like me to look at.

**Comment by chrisns** [comment]
amazing, i'll have a look asap and figure how to make it get built everytime

**Comment by chrisns** [comment]
merging, will figure out how to make dockerhub build on pushes to `node-sonos` too

**Pull request merged**
